# Generated by Django 3.2.16 on 2023-07-31 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0015_alter_about_about_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='skill',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
